Repository Rostlab/JS18_ProjectA_Group1, pull requests merged in 2018-03, with the labels that each got.

#28 UI basic setup
  client/index.html
  client/public/css/main.css
  client/public/index.html
  client/scss/main.scss
Labels: Setup GUI

#31 added client code to GET the graph data for a input from the server
  .idea/JS.iml
  .idea/runConfigurations/start.xml
  client/index.html
  client/js/app.js
  client/public/css/main.css
  client/public/index.html
  client/public/js/application.js
  client/public/librarys/getmdl-select.min.css
  client/public/librarys/getmdl-select.min.css.map
  client/public/librarys/getmdl-select.min.js
  client/public/librarys/getmdl-select.min.js.map
  client/public/librarys/material.min.css
  client/public/librarys/material.min.css.map
  client/public/librarys/material.min.js
  client/public/librarys/material.min.js.map
  client/public/librarys/plotly-latest.min.js
  client/scss/flexboxgrid.scss
  client/scss/main.scss
  client/scss/normalize.scss
  package-lock.json
  package.json
  server/controllers/contact.js
  server/controllers/nlp.js
  server/controllers/public.js
  server/data/commands.json
  server/migrations/migrations.js
  server/server.js
  server/test/unit/app.test.js
Labels: Simple Plot

#60 bug 49 - display bug at top bar
  client/js/app.js
  client/public/js/application.js
  package-lock.json
Labels: Bug

#73 merge to test changes
  package-lock.json
  package.json
Labels: work in progress

#81 ui for history
  client/index.html
  client/js/app.js
  client/public/css/main.css
  client/public/index.html
  client/public/js/application.js
  package-lock.json
Labels: Enhancement, Setup GUI
